In [2]:
a = [1,2,3,4]
b = [2,3,4,5]
print(a)
print(b)

[1, 2, 3, 4]
[2, 3, 4, 5]


In [3]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [5]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [98]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [77]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
np.transpose(np.concatenate([x, y])).ndim

1

In [106]:
v = np.arange(0, 30, 3)
al_getir = [1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [109]:
import pandas as pd
a = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [128]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [138]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [139]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [140]:
df = pd.DataFrame(sozluk)

In [143]:
df

var1  var2  var3
0     8     9     0
1     2     9     0
2     5     0     0
3     8     0     3
4     9     8     9

In [150]:
df.drop("var1", axis = 1)

var2  var3
0     9     0
1     9     0
2     0     0
3     0     3
4     8     9

In [147]:
df

var1  var2  var3
0     8     9     0
1     2     9     0
2     5     0     0
3     8     0     3
4     9     8     9